/* Generated by Yosys 0.66+142 (git sha1 fe8f29b5f, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "Finite_State_Machine.v:1.1-44.10" *)
module Finite_State_Machine(y, x, rst, clk);
  (* src = "Finite_State_Machine.v:3.8-3.9" *)
  output y;
  wire y;
  (* src = "Finite_State_Machine.v:2.7-2.8" *)
  input x;
  wire x;
  (* src = "Finite_State_Machine.v:2.9-2.12" *)
  input rst;
  wire rst;
  (* src = "Finite_State_Machine.v:2.13-2.16" *)
  input clk;
  wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "Finite_State_Machine.v:4.10-4.15" *)
  wire _04_;
  (* src = "Finite_State_Machine.v:4.10-4.15" *)
  wire _05_;
  (* src = "Finite_State_Machine.v:2.7-2.8" *)
  wire _06_;
  (* src = "Finite_State_Machine.v:3.8-3.9" *)
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire [1:0] _20_;
  wire [1:0] _21_;
  wire [1:0] _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "Finite_State_Machine.v:43.13-43.19" *)
  wire _32_;
  (* src = "Finite_State_Machine.v:43.25-43.35" *)
  wire _33_;
  wire [1:0] _34_;
  wire _35_;
  wire [1:0] _36_;
  wire _37_;
  wire [1:0] _38_;
  wire _39_;
  wire [1:0] _40_;
  (* src = "Finite_State_Machine.v:4.10-4.15" *)
  reg [1:0] state;
  assign _00_ = _04_ & ~(_06_);
  assign _01_ = _05_ & ~(_04_);
  assign _03_ = _06_ ? _01_ : _04_;
  assign _07_ = _05_ & _00_;
  (* src = "Finite_State_Machine.v:10.1-42.4" *)
  always @(posedge clk)
    if (rst) state[0] <= 1'h0;
    else state[0] <= _40_[0];
  (* src = "Finite_State_Machine.v:10.1-42.4" *)
  always @(posedge clk)
    if (rst) state[1] <= 1'h0;
    else state[1] <= _40_[1];
  assign _02_ = _06_;
  assign _04_ = state[0];
  assign _05_ = state[1];
  assign _06_ = x;
  assign _40_[0] = _02_;
  assign _40_[1] = _03_;
  assign y = _07_;
endmodule
